<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vassetmanager\Module'                      => __DIR__ . '/Module.php',
    'Vassetmanager\Controller\IndexController'  => __DIR__ . '/src/Vassetmanager/Controller/IndexController.php',
    'VassetmanagerTest\Framework\TestCase'      => __DIR__ . '/tests/Vassetmanager/Framework/TestCase.php',
    'VassetmanagerTest\SampleTest'              => __DIR__ . '/tests/Vassetmanager/SampleTest.php',
);
